In [1]:
from petl import look, fromdb, fromjson,  unpackdict, fromdicts, cut, rename, tocsv
from pandas import DataFrame
import pandas as pd
import numpy as np
import csv
import csv as reader
import sqlite3 as sql
import psycopg2 as pc
import mysql.connector 
import requests, urllib, json

In [2]:
#extracting CSV file from the computer
csv_dl = pd.read_csv('forestfires - ff_csv_dl.csv')
csv_dl.head()

data_entry  xx  yy month  day  ffmc   dmc     dc  isi  temp  rh  wind  \
0           1   7   5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   
1           2   7   4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   
2           3   7   4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   
3           4   8   6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   
4           5   8   6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   

   rain  area  
0   0.0     0  
1   0.0     0  
2   0.0     0  
3   0.2     0  
4   0.0     0

In [3]:
csv_dl.tail()

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
45          46   5   6   sep  wed  94.3   85.1  692.3  15.9  25.9  24   4.0   
46          47   5   6   sep  mon  90.9  126.5  686.5   7.0  14.7  70   3.6   
47          48   6   6   jul  mon  94.2   62.3  442.9  11.0  23.0  36   3.1   
48          49   4   4   mar  mon  87.2   23.9   64.7   4.1  11.8  35   1.8   
49          50   4   4   mar  mon  87.6   52.2  103.8   5.0  11.0  46   5.8   

    rain  area  
45   0.0     0  
46   0.0     0  
47   0.0     0  
48   0.0     0  
49   0.0     0

In [4]:
ff_dl = pd.DataFrame(csv_dl)
ff_dl

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
0            1   7   5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   
1            2   7   4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   
2            3   7   4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   
3            4   8   6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   
4            5   8   6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   
5            6   8   6   aug  sun  92.3   85.3  488.0  14.7  22.2  29   5.4   
6            7   8   6   aug  mon  92.3   88.9  495.6   8.5  24.1  27   3.1   
7            8   8   6   aug  mon  91.5  145.4  608.2  10.7   8.0  86   2.2   
8            9   8   6   sep  tue  91.0  129.5  692.6   7.0  13.1  63   5.4   
9           10   7   5   sep  sat  92.5   88.0  698.6   7.1  22.8  40   4.0   
10          11   7   5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   
11          12   7   5   sep  sat  92.8   73.2  713.0  22.6  19.3  38   4.0   
12          13   6   5   aug  fri  63.5   70.8  665.3   0.8  17.0  72   6.7   
13          14   6   5   sep  mon  90.9  126.5  686.5   7.0  21.3  42   2.2   
14          15   6   5   sep  wed  92.9  133.3  699.6   9.2  26.4  21   4.5   
15          16   6   5   sep  fri  93.3  141.2  713.9  13.9  22.9  44   5.4   
16          17   5   5   mar  sat  91.7   35.8   80.8   7.8  15.1  27   5.4   
17          18   8   5   oct  mon  84.9   32.8  664.2   3.0  16.7  47   4.9   
18          19   6   4   mar  wed  89.2   27.9   70.8   6.3  15.9  35   4.0   
19          20   6   4   apr  sat  86.3   27.4   97.1   5.1   9.3  44   4.5   
20          21   6   4   sep  tue  91.0  129.5  692.6   7.0  18.3  40   2.7   
21          22   5   4   sep  mon  91.8   78.5  724.3   9.2  19.1  38   2.7   
22          23   7   4   jun  sun  94.3   96.3  200.0  56.1  21.0  44   4.5   
23          24   7   4   aug  sat  90.2  110.9  537.4   6.2  19.5  43   5.8   
24          25   7   4   aug  sat  93.5  139.4  594.2  20.3  23.7  32   5.8   
25          26   7   4   aug  sun  91.4  142.4  601.4  10.6  16.3  60   5.4   
26          27   7   4   sep  fri  92.4  117.9  668.0  12.2  19.0  34   5.8   
27          28   7   4   sep  mon  90.9  126.5  686.5   7.0  19.4  48   1.3   
28          29   6   3   sep  sat  93.4  145.4  721.4   8.1  30.2  24   2.7   
29          30   6   3   sep  sun  93.5  149.3  728.6   8.1  22.8  39   3.6   
30          31   6   3   sep  fri  94.3   85.1  692.3  15.9  25.4  24   3.6   
31          32   6   3   sep  mon  88.6   91.8  709.9   7.1  11.2  78   7.6   
32          33   6   3   sep  fri  88.6   69.7  706.8   5.8  20.6  37   1.8   
33          34   6   3   sep  sun  91.7   75.6  718.3   7.8  17.7  39   3.6   
34          35   6   3   sep  mon  91.8   78.5  724.3   9.2  21.2  32   2.7   
35          36   6   3   sep  tue  90.3   80.7  730.2   6.3  18.2  62   4.5   
36          37   6   3   oct  tue  90.6   35.4  669.1   6.7  21.7  24   4.5   
37          38   7   4   oct  fri  90.0   41.5  682.6   8.7  11.3  60   5.4   
38          39   7   3   oct  sat  90.6   43.7  686.9   6.7  17.8  27   4.0   
39          40   4   4   mar  tue  88.1   25.7   67.6   3.8  14.1  43   2.7   
40          41   4   4   jul  tue  79.5   60.6  366.7   1.5  23.3  37   3.1   
41          42   4   4   aug  sat  90.2   96.9  624.2   8.9  18.4  42   6.7   
42          43   4   4   aug  tue  94.8  108.3  647.1  17.0  16.6  54   5.4   
43          44   4   4   sep  sat  92.5   88.0  698.6   7.1  19.6  48   2.7   
44          45   4   4   sep  wed  90.1   82.9  735.7   6.2  12.9  74   4.9   
45          46   5   6   sep  wed  94.3   85.1  692.3  15.9  25.9  24   4.0   
46          47   5   6   sep  mon  90.9  126.5  686.5   7.0  14.7  70   3.6   
47          48   6   6   jul  mon  94.2   62.3  442.9  11.0  23.0  36   3.1   
48          49   4   4   mar  mon  87.2   23.9   64.7   4.1  11.8  35   1.8   
49          50   4   4   mar  mon  87.6   52.2  103.8 

In [4]:
#extracting CSV file from the Google Drive
#id is 1jFf6RzUtIEnzq1rmbKrNhsiZAEyIqFG5
url = 'https://drive.google.com/file/d/1jFf6RzUtIEnzq1rmbKrNhsiZAEyIqFG5/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id=' + url.split('/')[-2]
path

'https://drive.google.com/uc?export=download&id=1jFf6RzUtIEnzq1rmbKrNhsiZAEyIqFG5'

In [5]:
csv_gdrive = pd.read_csv(path)
csv_gdrive.head()

data_entry  xx  yy month  day  ffmc    dmc     dc  isi  temp  rh  wind  \
0          51   4   4   sep  thu  92.9  137.0  706.4  9.2  20.8  17   1.3   
1          52   4   3   aug  sun  90.2   99.6  631.2  6.3  21.5  34   2.2   
2          53   4   3   aug  wed  92.1  111.2  654.1  9.6  20.4  42   4.9   
3          54   4   3   aug  wed  92.1  111.2  654.1  9.6  20.4  42   4.9   
4          55   4   3   aug  thu  91.7  114.3  661.3  6.3  17.6  45   3.6   

   rain  area  
0     0     0  
1     0     0  
2     0     0  
3     0     0  
4     0     0

In [7]:
csv_gdrive.tail()

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
45          96   4   4   sep  sun  89.7   90.0  704.4   4.8  17.8  64   1.3   
46          97   3   4   feb  sat  83.9    8.0   30.2   2.6  12.7  48   1.8   
47          98   3   4   mar  sat  69.0    2.4   15.5   0.7  17.4  24   5.4   
48          99   3   4   aug  sun  91.4  142.4  601.4  10.6  11.6  87   4.5   
49         100   3   4   aug  sun  91.4  142.4  601.4  10.6  19.8  39   5.4   

    rain  area  
45     0     0  
46     0     0  
47     0     0  
48     0     0  
49     0     0

In [6]:
ff_gdrive = pd.DataFrame(csv_gdrive)
ff_gdrive

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
0           51   4   4   sep  thu  92.9  137.0  706.4   9.2  20.8  17   1.3   
1           52   4   3   aug  sun  90.2   99.6  631.2   6.3  21.5  34   2.2   
2           53   4   3   aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   
3           54   4   3   aug  wed  92.1  111.2  654.1   9.6  20.4  42   4.9   
4           55   4   3   aug  thu  91.7  114.3  661.3   6.3  17.6  45   3.6   
5           56   4   3   sep  thu  92.9  137.0  706.4   9.2  27.7  24   2.2   
6           57   4   3   sep  tue  90.3   80.7  730.2   6.3  17.8  63   4.9   
7           58   4   3   oct  sun  92.6   46.5  691.8   8.8  13.8  50   2.7   
8           59   2   2   feb  mon  84.0    9.3   34.0   2.1  13.9  40   5.4   
9           60   2   2   feb  fri  86.6   13.2   43.0   5.3  12.3  51   0.9   
10          61   2   2   mar  sun  89.3   51.3  102.2   9.6  11.5  39   5.8   
11          62   2   2   mar  sun  89.3   51.3  102.2   9.6   5.5  59   6.3   
12          63   2   2   aug  thu  93.0   75.3  466.6   7.7  18.8  35   4.9   
13          64   2   2   aug  sun  90.2   99.6  631.2   6.3  20.8  33   2.7   
14          65   2   2   aug  mon  91.1  103.2  638.8   5.8  23.1  31   3.1   
15          66   2   2   aug  thu  91.7  114.3  661.3   6.3  18.6  44   4.5   
16          67   2   2   sep  fri  92.4  117.9  668.0  12.2  23.0  37   4.5   
17          68   2   2   sep  fri  92.4  117.9  668.0  12.2  19.6  33   5.4   
18          69   2   2   sep  fri  92.4  117.9  668.0  12.2  19.6  33   6.3   
19          70   4   5   mar  fri  91.7   33.3   77.5   9.0  17.2  26   4.5   
20          71   4   5   mar  fri  91.2   48.3   97.8  12.5  15.8  27   7.6   
21          72   4   5   sep  fri  94.3   85.1  692.3  15.9  17.7  37   3.6   
22          73   5   4   mar  fri  91.7   33.3   77.5   9.0  15.6  25   6.3   
23          74   5   4   aug  tue  88.8  147.3  614.5   9.0  17.3  43   4.5   
24          75   5   4   sep  fri  93.3  141.2  713.9  13.9  27.6  30   1.3   
25          76   9   9   feb  thu  84.2    6.8   26.6   7.7   6.7  79   3.1   
26          77   9   9   feb  fri  86.6   13.2   43.0   5.3  15.7  43   3.1   
27          78   1   3   mar  mon  87.6   52.2  103.8   5.0   8.3  72   3.1   
28          79   1   2   aug  fri  90.1  108.0  529.8  12.5  14.7  66   2.7   
29          80   1   2   aug  tue  91.0  121.2  561.6   7.0  21.6  19   6.7   
30          81   1   2   aug  sun  91.4  142.4  601.4  10.6  19.5  39   6.3   
31          82   1   2   aug  sun  90.2   99.6  631.2   6.3  17.9  44   2.2   
32          83   1   2   aug  tue  94.8  108.3  647.1  17.0  18.6  51   4.5   
33          84   1   2   aug  wed  92.1  111.2  654.1   9.6  16.6  47   0.9   
34          85   1   2   aug  thu  91.7  114.3  661.3   6.3  20.2  45   3.6   
35          86   1   2   sep  thu  92.9  137.0  706.4   9.2  21.5  15   0.9   
36          87   1   2   sep  thu  92.9  137.0  706.4   9.2  25.4  27   2.2   
37          88   1   2   sep  thu  92.9  137.0  706.4   9.2  22.4  34   2.2   
38          89   1   2   sep  sun  93.5  149.3  728.6   8.1  25.3  36   3.6   
39          90   6   5   mar  sat  91.7   35.8   80.8   7.8  17.4  25   4.9   
40          91   6   5   aug  sat  90.2   96.9  624.2   8.9  14.7  59   5.8   
41          92   8   6   mar  fri  91.7   35.8   80.8   7.8  17.4  24   5.4   
42          93   8   6   aug  sun  92.3   85.3  488.0  14.7  20.8  32   6.3   
43          94   8   6   aug  sun  91.4  142.4  601.4  10.6  18.2  43   4.9   
44          95   8   6   aug  mon  91.1  103.2  638.8   5.8  23.4  22   2.7   
45          96   4   4   sep  sun  89.7   90.0  704.4   4.8  17.8  64   1.3   
46          97   3   4   feb  sat  83.9    8.0   30.2   2.6  12.7  48   1.8   
47          98   3   4   mar  sat  69.0    2.4   15.5   0.7  17.4  24   5.4   
48          99   3   4   aug  sun  91.4  142.4  601.4  10.6  11.6  87   4.5   
49         100   3   4   aug  sun  91.4  142.4  601.4 

In [18]:
#SQLITE EXTRACTION
conn_sqlite = sql.connect('forestfiredb(sqlite).db')

In [19]:
cursor = conn_sqlite.cursor()

In [20]:
csv_sqlite = pd.read_csv('forestfires - ff_sqlite.csv')

In [21]:
csv_sqlite.to_sql(name = 'ff_sqlite', con = conn_sqlite, index = False, if_exists = 'replace')

In [22]:
df_sqlite = pd.read_sql_query('SELECT * FROM ff_sqlite', conn_sqlite)
df_sqlite.head()

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
0         101   3   4   aug  sun  91.4  142.4  601.4  10.6  19.8  39   5.4   
1         102   3   4   aug  tue  88.8  147.3  614.5   9.0  14.4  66   5.4   
2         103   2   4   aug  tue  94.8  108.3  647.1  17.0  20.1  40   4.0   
3         104   2   4   sep  sat  92.5  121.1  674.4   8.6  24.1  29   4.5   
4         105   2   4   jan  sat  82.1    3.7    9.3   2.9   5.3  78   3.1   

   rain  area  
0     0   0.0  
1     0   0.0  
2     0   0.0  
3     0   0.0  
4     0   0.0

In [23]:
df_sqlite.tail()

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
95         196   2   5   aug  fri  93.9  135.7  586.7  15.1  23.5  36   5.4   
96         197   6   5   apr  thu  81.5    9.1   55.2   2.7   5.8  54   5.8   
97         198   4   5   sep  thu  92.9  137.0  706.4   9.2  21.5  15   0.9   
98         199   3   4   sep  tue  91.0  129.5  692.6   7.0  13.9  59   6.3   
99         200   2   4   sep  mon  63.5   70.8  665.3   0.8  22.6  38   3.6   

    rain   area  
95     0  10.02  
96     0  10.93  
97     0  11.06  
98     0  11.24  
99     0  11.32

In [24]:
#POSTGRESQL EXTRACTION
conn_postgres = pc.connect("dbname = ff_postgres user = postgres password = @Ngelo8998 host = localhost")
c_postgres = conn_postgres.cursor()

In [25]:
from sqlalchemy import create_engine

In [26]:
engine_postgres = create_engine('postgresql+psycopg2://postgres:@Ngelo8998@localhost:5432/ff_postgres')

In [27]:
csv_postgres = pd.read_csv('forestfires - ff_pg.csv')

In [24]:
csv_postgres.to_sql('ff_postgres', engine_postgres, index = False, if_exists = 'replace')

In [28]:
df_postgres = pd.read_sql_query('SELECT * FROM ff_postgres', conn_postgres)
df_postgres.head()

data_entry  xx  yy month  day  ffmc    dmc     dc  isi  temp  rh  wind  \
0         201   1   5   sep  tue  91.0  129.5  692.6  7.0  21.6  33   2.2   
1         202   6   5   mar  sun  90.1   37.6   83.7  7.2  12.4  54   3.6   
2         203   7   4   feb  sun  83.9    8.7   32.1  2.1   8.8  68   2.2   
3         204   8   6   oct  wed  91.4   37.9  673.8  5.2  20.2  37   2.7   
4         205   5   6   mar  sat  90.6   50.1  100.4  7.8  15.1  64   4.0   

   rain   area  
0   0.0  11.53  
1   0.0  12.10  
2   0.0  13.05  
3   0.0  13.70  
4   0.0  13.99

In [27]:
df_postgres.tail()

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
195         396   4   5   feb  sun  85.0    9.0   56.9   3.5  10.1  62   1.8   
196         397   4   3   sep  sun  90.5   96.7  750.5  11.4  20.4  55   4.9   
197         398   5   6   aug  sun  91.6  181.3  613.0   7.6  24.3  33   3.6   
198         399   1   2   aug  sat  93.7  231.1  715.1   8.4  25.9  32   3.1   
199         400   9   5   jun  wed  93.3   49.5  297.7  14.0  28.0  34   4.5   

     rain   area  
195   0.0  51.78  
196   0.0   3.64  
197   0.0   3.63  
198   0.0   0.00  
199   0.0   0.00

In [29]:
#MYSQL EXTRACTION
conn_mysql = mysql.connector.connect(
    host = "localhost", 
    user = "root", 
    password = "@Ngelo8998",
    database = "ff_mysql"
)

In [30]:
c_mysql = conn_mysql.cursor()

In [31]:
engine_mysql = create_engine('mysql+mysqlconnector://root:@Ngelo8998@localhost:3306/ff_mysql')

In [32]:
csv_mysql = pd.read_csv('forestfires - ff_mysql.csv')

In [34]:
csv_mysql.to_sql("ff_mysql", engine_mysql, index = False, if_exists = "replace")

In [33]:
df_mysql = pd.read_sql_query('SELECT * FROM ff_mysql', conn_mysql)
df_mysql.head()

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
0         401   9   5   jun  wed  93.3   49.5  297.7  14.0  28.0  34   4.5   
1         402   3   4   sep  thu  91.1   88.2  731.7   8.3  22.8  46   4.0   
2         403   9   9   aug  fri  94.8  227.0  706.7  12.0  25.0  36   4.0   
3         404   8   6   aug  thu  90.7  194.1  643.0   6.8  21.3  41   3.6   
4         405   2   4   sep  wed  87.9   84.8  725.1   3.7  21.8  34   2.2   

   rain  area  
0   0.0  8.16  
1   0.0  4.95  
2   0.0  0.00  
3   0.0  0.00  
4   0.0  6.04

In [36]:
df_mysql.tail()

data_entry  xx  yy month  day  ffmc    dmc     dc  isi  temp  rh  wind  \
110         511   6   5   aug  fri  91.0  166.9  752.6  7.1  18.2  62   5.4   
111         512   8   6   aug  sun  81.6   56.7  665.6  1.9  27.8  35   2.7   
112         513   4   3   aug  sun  81.6   56.7  665.6  1.9  27.8  32   2.7   
113         514   2   4   aug  sun  81.6   56.7  665.6  1.9  21.9  71   5.8   
114         515   7   4   aug  sun  81.6   56.7  665.6  1.9  21.2  70   6.7   

     rain   area  
110   0.0   0.43  
111   0.0   0.00  
112   0.0   6.44  
113   0.0  54.29  
114   0.0  11.16

In [34]:
#local JSON extraction
#link https://csvjson.com/csv2json
with open('forestfires - ff_json.json') as fp:
    data = json.load(fp)

In [35]:
ff_json = pd.DataFrame(data)
ff_json

data_entry  xx  yy month  day  ffmc  dmc     dc   isi  temp  rh  wind  \
0         516   1   4   aug  sat  94.4  146  614.7  11.3  25.6  42   4.0   
1         517   6   3   nov  tue  79.5    3  106.7   1.1  11.8  31   4.5   

   rain  area  
0     0     0  
1     0     0

In [36]:
ff_complete = pd.concat([csv_dl, csv_gdrive, df_sqlite, df_postgres, df_mysql, ff_json])

In [37]:
ff_complete.head()

data_entry  xx  yy month  day  ffmc   dmc     dc  isi  temp  rh  wind  \
0           1   7   5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   
1           2   7   4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   
2           3   7   4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   
3           4   8   6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   
4           5   8   6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   

   rain  area  
0   0.0   0.0  
1   0.0   0.0  
2   0.0   0.0  
3   0.2   0.0  
4   0.0   0.0

In [27]:
ff_complete.tail()

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
112         513   4   3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   
113         514   2   4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   
114         515   7   4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   
0           516   1   4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   
1           517   6   3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   

     rain   area  
112   0.0   6.44  
113   0.0  54.29  
114   0.0  11.16  
0     0.0   0.00  
1     0.0   0.00

In [30]:
ff_complete

data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  wind  \
0             1   7   5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   
1             2   7   4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   0.9   
2             3   7   4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   1.3   
3             4   8   6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   4.0   
4             5   8   6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   1.8   
..          ...  ..  ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   
112         513   4   3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   2.7   
113         514   2   4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   5.8   
114         515   7   4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   6.7   
0           516   1   4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   4.0   
1           517   6   3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   4.5   

     rain   area  
0     0.0   0.00  
1     0.0   0.00  
2     0.0   0.00  
3     0.2   0.00  
4     0.0   0.00  
..    ...    ...  
112   0.0   6.44  
113   0.0  54.29  
114   0.0  11.16  
0     0.0   0.00  
1     0.0   0.00  

[517 rows x 14 columns]

In [62]:
ff_complete_2 = ff_complete.reset_index()
ff_complete_2

index  data_entry  xx  yy month  day  ffmc    dmc     dc   isi  temp  rh  \
0        0           1   7   5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   
1        1           2   7   4   oct  tue  90.6   35.4  669.1   6.7  18.0  33   
2        2           3   7   4   oct  sat  90.6   43.7  686.9   6.7  14.6  33   
3        3           4   8   6   mar  fri  91.7   33.3   77.5   9.0   8.3  97   
4        4           5   8   6   mar  sun  89.3   51.3  102.2   9.6  11.4  99   
..     ...         ...  ..  ..   ...  ...   ...    ...    ...   ...   ...  ..   
512    112         513   4   3   aug  sun  81.6   56.7  665.6   1.9  27.8  32   
513    113         514   2   4   aug  sun  81.6   56.7  665.6   1.9  21.9  71   
514    114         515   7   4   aug  sun  81.6   56.7  665.6   1.9  21.2  70   
515      0         516   1   4   aug  sat  94.4  146.0  614.7  11.3  25.6  42   
516      1         517   6   3   nov  tue  79.5    3.0  106.7   1.1  11.8  31   

     wind  rain   area  
0     6.7   0.0   0.00  
1     0.9   0.0   0.00  
2     1.3   0.0   0.00  
3     4.0   0.2   0.00  
4     1.8   0.0   0.00  
..    ...   ...    ...  
512   2.7   0.0   6.44  
513   5.8   0.0  54.29  
514   6.7   0.0  11.16  
515   4.0   0.0   0.00  
516   4.5   0.0   0.00  

[517 rows x 15 columns]

In [63]:
#REDUCING IS NOT NECESSARILY REMOVING A COLUMN
#REDUCTION IS ONLY APPLICABLE TO NUMERICAL
#TRANSFORMATION FROM CATEGORICAL TO NUMERICAL
#ARRANGED ALPHABETICALLY NOT BY COMMON SENSE SUCH AS JANUARY = 1 INSTEAD AUGUST = 1 IS THE CORRECT ONE


#Transformation
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [64]:
ff_complete_2.describe()

index  data_entry          xx          yy        ffmc         dmc  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean    65.485493  259.000000    4.669246    4.299807   90.644681  110.872340   
std     50.944360  149.389312    2.313778    1.229900    5.520111   64.046482   
min      0.000000    1.000000    1.000000    2.000000   18.700000    1.100000   
25%     25.000000  130.000000    3.000000    4.000000   90.200000   68.600000   
50%     52.000000  259.000000    4.000000    4.000000   91.600000  108.300000   
75%     95.000000  388.000000    7.000000    5.000000   92.900000  142.400000   
max    199.000000  517.000000    9.000000    9.000000   96.200000  291.300000   

               dc         isi        temp          rh        wind        rain  \
count  517.000000  517.000000  517.000000  517.000000  517.000000  517.000000   
mean   547.940039    9.021663   18.889168   44.288201    4.017602    0.021663   
std    248.066192    4.559477    5.806625   16.317469    1.791653    0.295959   
min      7.900000    0.000000    2.200000   15.000000    0.400000    0.000000   
25%    437.700000    6.500000   15.500000   33.000000    2.700000    0.000000   
50%    664.200000    8.400000   19.300000   42.000000    4.000000    0.000000   
75%    713.900000   10.800000   22.800000   53.000000    4.900000    0.000000   
max    860.600000   56.100000   33.300000  100.000000    9.400000    6.400000   

              area  
count   517.000000  
mean     12.847292  
std      63.655818  
min       0.000000  
25%       0.000000  
50%       0.520000  
75%       6.570000  
max    1090.840000

In [65]:
ff_complete_2.dtypes

index           int64
data_entry      int64
xx              int64
yy              int64
month          object
day            object
ffmc          float64
dmc           float64
dc            float64
isi           float64
temp          float64
rh              int64
wind          float64
rain          float64
area          float64
dtype: object

In [66]:
#Double tranformation is possible
ff = LabelEncoder()
ff_complete_2['month'] = ff.fit_transform(ff_complete_2['month'].astype('str'))
ff_complete_2['day'] = ff.fit_transform(ff_complete_2['day'].astype('str'))
ff_complete_2

index  data_entry  xx  yy  month  day  ffmc    dmc     dc   isi  temp  \
0        0           1   7   5      7    0  86.2   26.2   94.3   5.1   8.2   
1        1           2   7   4     10    5  90.6   35.4  669.1   6.7  18.0   
2        2           3   7   4     10    2  90.6   43.7  686.9   6.7  14.6   
3        3           4   8   6      7    0  91.7   33.3   77.5   9.0   8.3   
4        4           5   8   6      7    3  89.3   51.3  102.2   9.6  11.4   
..     ...         ...  ..  ..    ...  ...   ...    ...    ...   ...   ...   
512    112         513   4   3      1    3  81.6   56.7  665.6   1.9  27.8   
513    113         514   2   4      1    3  81.6   56.7  665.6   1.9  21.9   
514    114         515   7   4      1    3  81.6   56.7  665.6   1.9  21.2   
515      0         516   1   4      1    2  94.4  146.0  614.7  11.3  25.6   
516      1         517   6   3      9    5  79.5    3.0  106.7   1.1  11.8   

     rh  wind  rain   area  
0    51   6.7   0.0   0.00  
1    33   0.9   0.0   0.00  
2    33   1.3   0.0   0.00  
3    97   4.0   0.2   0.00  
4    99   1.8   0.0   0.00  
..   ..   ...   ...    ...  
512  32   2.7   0.0   6.44  
513  71   5.8   0.0  54.29  
514  70   6.7   0.0  11.16  
515  42   4.0   0.0   0.00  
516  31   4.5   0.0   0.00  

[517 rows x 15 columns]

In [67]:
# : means everything from 0 to 516 record
# iloc is used to get the values of recrods based from column and record number
# 1st paramter is x for record and 2nd parameter is y for column
x = ff_complete_2.iloc[:, 2:13].values
y = ff_complete_2.iloc[:, 14].values
y

array([0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.000

In [68]:
x

array([[ 7. ,  5. ,  7. , ...,  8.2, 51. ,  6.7],
       [ 7. ,  4. , 10. , ..., 18. , 33. ,  0.9],
       [ 7. ,  4. , 10. , ..., 14.6, 33. ,  1.3],
       ...,
       [ 7. ,  4. ,  1. , ..., 21.2, 70. ,  6.7],
       [ 1. ,  4. ,  1. , ..., 25.6, 42. ,  4. ],
       [ 6. ,  3. ,  9. , ..., 11.8, 31. ,  4.5]])

In [69]:
#Dimension reduction (principal component analysis)
from sklearn.decomposition import PCA

In [70]:
#Compresses x values from 2:13 to 5 
pca = PCA(n_components = 5)
pca_ff = pca.fit_transform(x)
new_ff_x = pd.DataFrame(data = pca_ff, columns = ['x1', 'x2', 'x3', 'x4', 'x5'])
new_ff_x.head()

x1         x2         x3         x4        x5
0  461.609452  -1.851030   6.942137   2.456834 -4.496038
1 -105.659077 -96.581758  -5.700820   0.443008 -0.877036
2 -124.616238 -91.700930  -5.093052   1.667573 -3.183901
3  476.903566  10.850221  50.094674 -11.067953 -3.867160
4  449.356526  24.202424  51.164537  -9.832406 -1.053004

In [71]:
new_ff_x.tail()

x1         x2         x3         x4         x5
512 -106.034641 -74.858915  -8.240433   7.717838  12.876789
513 -105.874824 -72.829180  30.752245   2.507554  11.979862
514 -105.863774 -72.891160  29.983684   2.661995  11.554834
515  -72.078441  22.829215  -4.774276  -3.957223   4.373971
516  453.541006 -28.177311 -11.065343  11.344406  -1.315126

In [72]:
#Compresses x values from 2:13 to 6 
pca = PCA(n_components = 6)
pca_ff = pca.fit_transform(x)
new_ff_x = pd.DataFrame(data = pca_ff, columns = ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'])
new_ff_x.head()

x1         x2         x3         x4        x5        x6
0  461.609452  -1.851030   6.942137   2.456834 -4.496038  1.011319
1 -105.659077 -96.581758  -5.700820   0.443008 -0.877036  0.885511
2 -124.616238 -91.700930  -5.093052   1.667573 -3.183901  3.291827
3  476.903566  10.850221  50.094674 -11.067953 -3.867160 -5.417805
4  449.356526  24.202424  51.164537  -9.832406 -1.053004 -8.189107

In [73]:
#Steps in performing the PCA
#1. Standardization 
ff_std_x = StandardScaler().fit_transform(x)
ff_std_x

array([[ 1.00831277,  0.56986043,  0.28422225, ..., -1.84264015,
         0.41172435,  1.49861442],
       [ 1.00831277, -0.24400101,  0.97087134, ..., -0.15327826,
        -0.69245628, -1.74175564],
       [ 1.00831277, -0.24400101,  0.97087134, ..., -0.73938341,
        -0.69245628, -1.51828184],
       ...,
       [ 1.00831277, -0.24400101, -1.08907592, ...,  0.3983501 ,
         1.57724834,  1.49861442],
       [-1.58736044, -0.24400101, -1.08907592, ...,  1.15683911,
        -0.14036597, -0.00983371],
       [ 0.57570057, -1.05786246,  0.74198831, ..., -1.22205823,
        -0.81514302,  0.26950853]])

In [74]:
#2 Compute the covariance matrix
mean_ff = np.mean(ff_std_x, axis = 0)

In [75]:
mean_ff

array([ 2.11307438e-16,  2.61127891e-16,  0.00000000e+00,  5.15383996e-17,
       -1.75230559e-15, -2.74871465e-17,  6.87178661e-17,  1.03076799e-17,
        2.54256105e-16,  2.19897172e-16, -4.19178983e-16])

In [77]:
# number of n (ff_std_x.shape[0]-1)
cov_ff = (ff_std_x - mean_ff).T.dot((ff_std_x - mean_ff))/(ff_std_x.shape[0]-1)
cov_ff

array([[ 1.00193798,  0.54059381, -0.01733658, -0.00914711, -0.02108005,
        -0.04847795, -0.08608263,  0.00622198, -0.0513576 ,  0.08538835,
         0.01883425],
       [ 0.54059381,  1.00193798, -0.06228226,  0.03015879, -0.04639729,
         0.00779664, -0.10137385, -0.02453545, -0.0241498 ,  0.06234131,
        -0.02038027],
       [-0.01733658, -0.06228226,  1.00193798, -0.15127441, -0.00765042,
        -0.17348726,  0.2198638 , -0.17242005, -0.07394541, -0.10225519,
        -0.14140414],
       [-0.00914711,  0.03015879, -0.15127441,  1.00193798,  0.07505929,
         0.07035426,  0.0588506 ,  0.11796667,  0.14896029, -0.10358984,
        -0.03457044],
       [-0.02108005, -0.04639729, -0.00765042,  0.07505929,  1.00193798,
         0.38336031,  0.33115232,  0.53283556,  0.43236856, -0.30157874,
        -0.02854001],
       [-0.04847795,  0.00779664, -0.17348726,  0.07035426,  0.38336031,
         1.00193798,  0.68351369,  0.30571917,  0.47050391,  0.07393795,
        -0.105

In [78]:
#2.1 Alternative covariance
#T means transpose
cov_ff2 = np.cov(ff_std_x.T)
cov_ff2

array([[ 1.00193798,  0.54059381, -0.01733658, -0.00914711, -0.02108005,
        -0.04847795, -0.08608263,  0.00622198, -0.0513576 ,  0.08538835,
         0.01883425],
       [ 0.54059381,  1.00193798, -0.06228226,  0.03015879, -0.04639729,
         0.00779664, -0.10137385, -0.02453545, -0.0241498 ,  0.06234131,
        -0.02038027],
       [-0.01733658, -0.06228226,  1.00193798, -0.15127441, -0.00765042,
        -0.17348726,  0.2198638 , -0.17242005, -0.07394541, -0.10225519,
        -0.14140414],
       [-0.00914711,  0.03015879, -0.15127441,  1.00193798,  0.07505929,
         0.07035426,  0.0588506 ,  0.11796667,  0.14896029, -0.10358984,
        -0.03457044],
       [-0.02108005, -0.04639729, -0.00765042,  0.07505929,  1.00193798,
         0.38336031,  0.33115232,  0.53283556,  0.43236856, -0.30157874,
        -0.02854001],
       [-0.04847795,  0.00779664, -0.17348726,  0.07035426,  0.38336031,
         1.00193798,  0.68351369,  0.30571917,  0.47050391,  0.07393795,
        -0.105

In [79]:
#3 Compute the eigenvalues and eigenvectors of the covariance metrix to 
    #identify the principal components eig_vals
eig_vals, eig_vecs = np.linalg.eig(cov_ff)
eig_vals

array([2.89018255, 1.58108541, 1.36935574, 1.28567525, 1.05064497,
       0.20326891, 0.22120331, 0.44583539, 0.4651397 , 0.8165879 ,
       0.69233869])

In [80]:
eig_vecs

array([[-0.07875258, -0.62811305,  0.25327254,  0.14143078,  0.13795369,
         0.0393424 ,  0.05468845,  0.50500434,  0.48047223, -0.07506352,
        -0.00591857],
       [-0.06838201, -0.63811069,  0.25657448,  0.14081573, -0.00314818,
        -0.09790043, -0.02001125, -0.49859932, -0.48209063,  0.02215936,
         0.10478819],
       [-0.02811191,  0.2996516 ,  0.51095928,  0.23818217,  0.36160807,
         0.34696449, -0.05817774, -0.16401171,  0.00727282, -0.55234712,
        -0.0709861 ],
       [ 0.12325239, -0.12789014, -0.22129757,  0.12352771, -0.68565348,
         0.0479909 , -0.01139354,  0.04829009, -0.02582257, -0.65270347,
        -0.05144949],
       [ 0.42054755, -0.07676799, -0.14501081,  0.10094769,  0.30850816,
        -0.09350954, -0.21015097,  0.45053745, -0.53245772, -0.08014704,
        -0.38082064],
       [ 0.42478804, -0.10689947,  0.13586234, -0.46245177, -0.07046777,
         0.59008125,  0.35931648,  0.09352811, -0.15854066,  0.07354717,
         0.232

In [81]:
#4 Create a featiure vector to decide which principal components to retain
#5 recast the data along the principal component
pca2 = PCA(n_components = 5)
pca_ff2 = pca2.fit_transform(ff_std_x)
new_ff_x2 = pd.DataFrame(data = pca_ff2, columns = ['x1', 'x2', 'x3', 'x4', 'x5'])
new_ff_x2.head()

x1        x2        x3        x4        x5
0  3.464406  0.736436  0.345121 -0.252229 -1.641998
1  0.122825 -0.227198 -1.423982 -1.612319  1.095452
2  0.540655 -0.403640 -1.679523 -1.167001 -0.128238
3  3.279272  1.964469 -0.598592  1.311556 -1.482602
4  2.679994  2.056438 -1.000132  1.108174  0.306828

In [82]:
#non-standardized
new_ff_x

x1         x2         x3         x4         x5        x6
0    461.609452  -1.851030   6.942137   2.456834  -4.496038  1.011319
1   -105.659077 -96.581758  -5.700820   0.443008  -0.877036  0.885511
2   -124.616238 -91.700930  -5.093052   1.667573  -3.183901  3.291827
3    476.903566  10.850221  50.094674 -11.067953  -3.867160 -5.417805
4    449.356526  24.202424  51.164537  -9.832406  -1.053004 -8.189107
..          ...        ...        ...        ...        ...       ...
512 -106.034641 -74.858915  -8.240433   7.717838  12.876789 -0.633944
513 -105.874824 -72.829180  30.752245   2.507554  11.979862 -1.206430
514 -105.863774 -72.891160  29.983684   2.661995  11.554834 -0.790692
515  -72.078441  22.829215  -4.774276  -3.957223   4.373971 -0.156384
516  453.541006 -28.177311 -11.065343  11.344406  -1.315126 -0.434097

[517 rows x 6 columns]